baseurl: https://bit.andirnu.ml
languageCode: ja-JP
theme: hugo-theme-stack
paginate: 3
title: ballenovの音ゲー日記

# Change it to your Disqus shortname before using
disqusShortname: ballenov

# GA Tracking ID
googleAnalytics: G-CNB29WRK9B

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: ja

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /posts/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText: 

    dateFormat:
        published: 2006年1月2日, 
        lastUpdated: 2006年1月2日 15時4分(MST)

    sidebar:
        emoji: ⚡
        subtitle: 音ゲー初心者
        avatar:
            enabled: true
            local: true
            src: /img/avatar.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner: 
            admin:  
            repo: 
            clientID: 
            clientSecret: 
        
        cusdis:
            host: 
            id: 

    widgets:
        enabled:
            # - search
            - archives
            - tag-cloud

        archives:
            limit: 5
            path: /archives

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: ballenov_kpr

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: ホーム
          url: /
          weight: -100
          pre: home
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
        - identifier: tags
          name: タグ
          url: /tags
          weight: -70
          pre: hash
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/ballenov_kpr
          weight: -60
          pre: twitter
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: true
        - identifier: youtube
          name: YouTube
          url: https://www.youtube.com/channel/UCU8fvo88cOaQ-kcCz9K0xUg
          weight: -50
          pre: youtube
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: true

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
